# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: p-common.org
#+INCLUDE: tikz/graph-common.org
#+LATEX_HEADER: \usepackage[margin=1.5cm]{geometry}

#+TITLE: Discrete mathematics II. practice - Graphs
#+SHORT_TITLE: Graphs
All graphs are simple and finite if not stated otherwise.
* Problems
  1. Draw all mutually not isomorphic graphs with 3, 4 and 5 vertices.
     Which of them are connected, which are regular graphs?
  2. Does a graph exist (with at least two vertices) with all vertices
     having different degrees?
  3. Can you find a group of people so each one of them has a different
     number of mutual friends (inside the group)?
  4. Are there graphs (arbitrary or simple) with 9 vertices with the
     following values for the degrees:
     1) $7,7,7,6,6,6,5,5,5$;
     2) $6,6,5,4,4,3,2,2,1$?
  5. Is there a graph with 8 vertices with degrees $6,6,6,6,3,3,2,2$?
  6. How many mutually not isomorphic graphs are there with:
     1) 2 vertices, each with degrees 2, 3 or 4?
     2) 3 vertices, each with degrees 2, 3 or 4?
  7. Show that the number of vertices with odd degrees is even.
  8. Draw the following graph!  Specify five points on a cycle!
     These points define $\binom{5}{2}$ chords which will be the
     vertices of the graph.  Two vertices in the graph are connected
     if and only if the corresponding chords don't have a common
     endpoint.  The obtained graph is called the Petersen graph.
  9. Which $C_n$'s are sub\-graphs of the Petersen graph?
  10. How many graphs with 3, 4 or 5 vertices are isomorphic to their
      own complement?
  11. Prove that any closed walk of odd length contains a cycle.  Is
      this true for closed walks of even length.
  12. Show that if all vertices in a graph have degrees of at least
      two, then the graph contains a cycle!
  13. Show that if there is a route from $a$ to $b$ and a route from
      $b$ to $c$ then there is a route from $a$ to $c$.
  14. Six contestants are competing in a tournament.  Prove that at
      any moment there are three players who all played against each
      other, or three players who didn't play with the other two.
  15. Show that if a graph has $2n$ vertices and all of them have
      degree at least $n$, then the graph is connected!  What happens
      if we allow vertices with degree $n-1$?
  16. Is it true, that either the graph $G$ or its complement is
      always connected?
  17. In a tree, let us denote the number of vertices with degree 1
      with $f_1$, and with degree more than 2 with $c$.  Show that if
      there are at least two vertices in the graph $f_1>c+2$ is true.
  18. Show that in a connected finite graph, each two routes of
      maximum length have at least one common vertex.
  19. Show that in a finite tree there is a vertex through which all
      the routes of maximum length go through.
  20. If the number of vertices in a graph is $n\ge1$, at least how
      many separating edges (edges which separate the graph into more
      components if they are removed) are there in the graph?  At
      least how many separating vertices?  For both cases provide an
      example where the number of separating edges (or vertices)
      equals to the bound.
  21. Show that in a finite graph the sum of the number of components
      and the number of edges is not less than the number of vertices.
  22. Can you draw the following graphs without lifting your pen and
      not going over any line more than once (is there an Euler line
      or closed line in the graph).

      \begin{tikzpicture}[scale=0.5]
      \draw[inode] (0,0) node{} 
      -- ++(0,1)  node{} 
      -- ++(-2,0) node{} 
      -- ++(0,3)  node{}
      -- ++(4,0)  node{} 
      -- ++(0,-3) node{}
      -- ++(-2,0) node{} 
      -- ++(0,1)  node{}
      -- ++(-1,0) node{} 
      -- ++(0,1)  node{}
      -- ++(2,0)  node{} 
      -- ++(0,-1) node{}
      -- ++(-1,0) node{} 
      -- ++(0,1)  node{}
      -- ++(0,1)  node{} 
      -- ++(0,1)  node{};
      \end{tikzpicture}

      \begin{tikzpicture}[scale=0.8,inode]
      \def\n{3}
      \foreach \x in {0,...,\n}{
      \draw (0,\x) -- (\n,\x);
      \draw (\x,0) -- (\x,\n);
      \foreach \y in {0,...,\n}{
      \node at (\x,\y) {};
      }
      }
      \draw (0,1) -- (1,0);
      \draw (2,0) -- (3,1);
      \draw (0,2) -- (1,3);
      \draw (2,3) -- (3,2);
      \end{tikzpicture}
  23. Does a graph exist which contains a closed Euler line and has an
      even number of vertices and odd number of edges.
  24. Show, that each connected graph contains a walk which contains
      each edge exactly twice.  Is it a closed walk?
  25. Show that if all vertices have degree 4 then the edges can be
      coloured red and blue so that each vertex is connected to two
      red and two blue edges.
  26. Are the following graphs Hamiltonian (or a Hamilton route):

      \begin{tikzpicture}[scale=0.65,inode]
      \foreach \s in {0+45,90+45,180+45,270+45}{
      \node at (\s:1) {};
      \node at (\s:2) {};
      \node at (\s:3) {};
      \node at (\s+45:1.41) {};
      \draw [-] 
      (\s:1) -- ({\s+90}:1)
      (\s:2) -- ({\s+90}:2)
      (\s:3) -- ({\s+90}:3)
      (\s:1) -- ({\s}:3);
      }
      \end{tikzpicture}

      \begin{tikzpicture}[scale=0.9]
      \filldraw
      (0:0) circle (3pt);
      \filldraw
      (0:1) circle (3pt)
      (72:1) circle (3pt)
      (144:1) circle (3pt)
      (216:1) circle (3pt)
      (288:1) circle (3pt);
      \filldraw
      (0:2) circle (3pt)
      (72:2) circle (3pt)
      (144:2) circle (3pt)
      (216:2) circle (3pt)
      (288:2) circle (3pt);
      
      \foreach \s in {0,72,144,216,288}{
      \draw [-] (\s:2) -- ({\s+72}:2);
      \draw [-] (\s:0) -- ({\s}:1);
      \draw [-] (\s:2) -- ({\s+72}:1);
      \draw [-] (\s:1) -- ({\s+72}:2);
      }
      \end{tikzpicture}

      \begin{tikzpicture}[scale=0.65]
      \foreach \s in {0,72,144,216,288}{
      \filldraw 
      (\s:1) circle (3pt)
      (\s:2) circle (3pt)
      ({\s+36}:1.63) circle (3pt)
      (\s:3) circle (3pt);
      
      \draw [-] 
      (\s:1) -- ({\s+72}:1)
      (\s:2) -- ({\s+72}:2)
      (\s:3) -- ({\s+72}:3)
      (\s:1) -- ({\s}:3);
      }
      \end{tikzpicture}
  27. Can you jump with a knight on a $9\times9$ chess board, touching
      all the squares and returning to the starting one at the end.
  28. Show that a pack of dominoes can be arranged in a cycle.
  29. Show that the Petersen graph is not Hamiltonian but deleting a
      vertex makes it Hamiltonian.
  30. Show that if a graph is Hamiltonian, then deleting one edge
      always leaves it connected.
  31. Show that if there are $k$ vertices which if removed split the
      graph up into more than $k$ components, then the original graph
      is not Hamiltonian.
  32. Show that if removing an edge from the cycle $K$ of a finite
      connected graph produces a route of maximum length, then $K$ was
      a Hamilton cycle.
  33. For all $n\ge 5$ show that there exists a graph $G$ with $n$
      vertices, 
      1) so that both $G$ and $\overline{G}$ is Hamiltonian;
      2) so that neither $G$ nor $\overline{G}$ are Hamiltonian.
  34. One hundred friends arrive at a hotel.  Each night they are
      seated at the same table.  Also each evening they get into a
      quarrel with their neighbors and get angry at each other (until
      the end of their lives).  Also, every evening they select their
      seats so that they don't sit next to someone who they are angry
      with.  When they can't sit down like this at the table, they all
      go home.  Show that they stay at the hotel for at least 25 days.
  35. Show that any graph not containing loops can be directed in a
      way that the resulting directed graph has no directed cycle.
  36. Show that after a tennis tournament all the players can stand in
      a line so that every player has defeated the person standing
      immediately in front off him/her.
      #  \item 37 TODO
      #  \item 38 TODO
  37. Which of these graphs can be drawn so that their edges don't
      intersect:
      1) the edges of a 3d cube; 
      2) $K_n$ for $n=3,4,5,\ldots$; 
      3) ``three houses, three wells'' \ie $K_{3,3}$;
      4) the Petersen graph.
  38. How many edges does a planar graph with $n$ vertices have if all
      of its faces are triangles.
  39. Show that a planar graph with at least $n\ge3$ vertices has at
      most $3n-6$ edges.
  40. Prove that if the graph $G$ has 11 or more vertices, then either
      $G$ or its complement is not planar!
  41. Draw a planar graph with 8 vertices so its complement is also
      planar!
  42. Show that a simple planar graph can not have all vertices with
      degree at least 6.
  43. At most how many edges does a planar graph have if all of its
      cycles are at least $k$ long.
  44. On an international conference representatives of 5 countries
      are sitting at a table.  That there are at least two of them not
      from neighboring countries!
  45. Show that the faces of a planar graph can be coloured with two
      colours so that adjacent faces have different colours if and
      only if the graph contains a closed Euler line.
* Solutions
  1. We did this for the practical session.
  2. No.  The possible degrees are: $0,1,2,\ldots,n-1$ (if
     $n=\card{V}$).  Bot $0$ and $n-1$ degree edges are not possible
     in a simple graph, one of the degrees has to repeat (because of
     the pigeon hole principle).
  3. No.  Same as the previous problem.
  4. 
     1) Yes.  Draw $K_6$ and $K_3$ and connect all vertices from $K_3$
        with all vertices from $K_6$ making the degrees in $K_3$ equal
        to $5$, and half of vertices in $K_6$ equal to $6$ and half to
        $7$.
     2) No.  $\sum_{v\in V} d(v)$ is odd.
  5. No.  If we connect all vertices with degree 6 into a complete
     graph \ie $K_4$, there are 12 edges which would need to be
     connected (for each vertex 3 edges connect to the other 3
     vertices in $K_4$ and there are 3 remaining, and $3\cdot 4=12$),
     ergo the vertices with 6 degrees need at least 12 (or more) edges
     to connect to.

     These edges can be provided by the vertices with $3, 3, 2, 2$
     degrees, but all together they can only provide $3+3+2+2=10$
     edges at most (which does not need the requirement of at least 12
     edges).
  6. We did this for the practical session.
  7. Trivial: because $\sum_{v\in V}d(v) = 2\card{E}$.
  8. Draw it. Homework. (We used the Petersen graph several times).
  9. The Petersen graph contains $C_5, C_6, C_8$ and $C_9$.  Find
     them.  To enter the "inner star" in the Petersen graph from an
     "outer point" and to return to the "outer pentagon" there are two ways:
     - to an adjacent vertex in 4 or 5 steps, then the cycle can be
       closed in 1 or 4 steps, resulting in $4+1=5$, $4+4=8$, $5+1=6$
       and $5+4=9$ long cycles; or
     - to a non-adjacent vertex in 3 or 6 steps, and close the cycle
       in 2 or 3 steps, resulting in $3+2=5$, $3+3=6$, $6+2=8$
       and $6+3=9$ long cycles.
     There are no other possibilities!
  10. There is no graph with 3 vertices isomorphic to its complement.
      There is one graph with 4 vertices isomorphic to its complement:

      \begin{tikzpicture}[inode]
      \draw (0,0) node{} 
      -- ++(1,0)  node{}
      -- ++(0,1)  node{}
      -- ++(-1,0)  node{}
      ;
      \draw (3,0) node{} 
      -- ++(-1,1)  node{}
      -- ++(0,-1)  node{}
      -- ++(1,1)  node{}
      ;
      \end{tikzpicture}

      There are two graph with 5 vertices isomorphic to its
      complement:

      \begin{tikzpicture}[inode]
      \draw (0:1) node{}
      -- (72:1) node{} 
      -- (2*72:1)  node{}
      -- (3*72:1)  node{}
      -- (4*72:1)  node{}
      -- (5*72:1)  node{}
      ;
      \draw[xshift=80] (0:1) node{}
      -- (2*72:1) node{} 
      -- (4*72:1)  node{}
      -- (1*72:1)  node{}
      -- (3*72:1)  node{}
      -- (5*72:1)  node{}
      ;
      \end{tikzpicture}
      
      and
      
      \begin{tikzpicture}[inode]
      \draw (0:1) node{}
      -- (1*72:1) node{} 
      -- (4*72:1)  node{}
      -- (0*72:1) node{}
      (4*72:1) node{}
      -- (3*72:1)  node{}
      (1*72:1)  node{}
      -- (2*72:1)  node{}
      ;
      \draw[xshift=80] 
      (0:1) node{}
      -- (2*72:1) node{} 
      -- (3*72:1)  node{}
      -- (0*72:1)  node{}
      (2*72:1)  node{}
      -- (4*72:1)  node{}
      (3*72:1)  node{}
      -- (1*72:1)  node{}
      ;
      \end{tikzpicture}
  11. Since the graph is finite, the following algorithm terminates in
      finite many steps and finds a cycle in the graph.
      1) Initialization: $S \gets$ closed cycle.
      2) Terminate?: if all the vertices in $S$ are different, we have
         a cycle, we are finished.
      3) Divide the closed walk: otherwise there is $i\neq j$ so that
         $v_i=v_j$.  At his vertex $S$ can be divided into two
         /shorter/ closed cycles, one even and one with odd length and
         let $S\gets$ the closed cycle with odd length.
      4) Go to the second step.
  12. Since the graph is finite, the following algorithm terminates in
      finite many steps and finds a cycle in the graph.
      1) Initialization: Let $R \gets \{v\}$ for some vertex $v$.
      2) Terminate?: if the last vertex added to $R$ has unused edge
         going back to $R$, adding that edge, gives us a cycle and we
         are done.
      3) Expand $R$: Since every vertex $v$ has $d(v)\ge 2$, after
         ``entering'' the vertex there has to be an unused ``leaving''
         edge from that vertex. Expand $R$ with that edge and the
         other unused vertex at its endpoint.
  13. If the route from $a$ to $b$ is
      $a=v_0,e_1,v_1,\ldots,e_n,v_n=b$, and the route from $b$ to $c$
      is $b=v'_0,e'_1,v'_1,\ldots,e'_n,v'_n=c$ then we have a /walk/
      (not a route) from $a$ to $c$, but we have learned (see
      lectures) that from every walk, by deleting $e_i,v_i$ pairs we
      can obtain a route with the same endpoints.
  14. Reformulate the problem to the domain of graphs: we need to
      prove for each 6 vertex simple graph $G$, there is triangle in
      $G$ or $\overline{G}$.  In $G\cup \overline{G}$ each vertex has
      $d(v)=5$ so in $G$ or $\overline{G}$, $v$ has at least $3$
      neighbors $v_1, v_2$ and $v_3$, let's suppose it is in $G$.
      Then if there is an edge in $G$ between two of the neighboring
      vertices, lets say $v_1$ and $v_2$ then there is a triangle
      $v,v_1,v2$ in $G$. Otherwise, if non of the edges are present
      between $v_1, v_2$ and $v_3$, then all three edges are present
      in $\overline{G}$ \ie there is a triangle $v_1, v_2, v_3$ in
      $\overline{G}$.
  15. Indirect proof:
      - If $G$ is not connected, it has at least two components.
      - The smaller component has at most $n$ vertices.
      - A component with $n$ vertices in a simple graph must have
	$d(v)\le n-1$ for all vertices, which is a contradiction (to
	$d(v)\ge n$ for all vertices).
      This will not be true for only $d(v)\ge n-1$.  For example:
      $n=1$, $2n+1=3$.  Then $3$ isolated vertices, \ie $d(v)=0=n-1$
      for each vertex, and the graph has 3 components, ergo it is not
      connected.
  16. If $G$ is connected we are done!  If $G$ is disconnected there
      are at least two components.  Any vertices $v$ and $v'$ are
      either in one component or in different components.
      - If $v$ and $v'$ are in different components, there and edge
	between them in $\overline{G}$.
      - If $v$ and $v'$ are in the same component, then there is at
        least one more component with at least one vertex in it, let's
        it be the vertex $z$.  $z$ is not connected to $v$ nor $v'$ in
        $G$, so in $\overline{G}$ there is a route from $v$ through
        $z$ to $v'$.
  17. Proofs:
      - Let $n=\card{V}$ \ie the number of vertices and
	\[f_i=\card{\{v\in V:d(v)=i\}}\] \ie $f_i$ is the number of
	vertices with degree $i$, with $d=\max\{d(v):v\in V\}$ then:
	\begin{align}
	n &= f_1+f_2+\cdots+f_d \label{f1one} \\
	\sum_{v\in V} d(v) &= f_1 + 2f_2 + \cdots +df_d \label{f1two}
	\end{align}
      - Because in a tree graph, the number of edges is $n-1$ ergo
	$\sum_{v\in V} d(v) = 2\card{E}=2n-2$.  So by multiplying
	\eqref{f1one} we get
	\begin{equation}
	\label{f1three}
	2n = 2f_1 + 2f_2 + \cdots 2f_d
	\end{equation}
	Subtracting \eqref{f1two} from \eqref{f1three} we get \[ 2 =
	f_1 - f_3 - 2f_4 - \cdots - (d-2)f_d \] or rearranging the
	previous equation: \[ f_1 = 2 + f_3 + 2f_4 + \cdots (d-2)f_d
	\ge 2 + c\] because 
	\begin{align*}
	c &= f_3 + f_4 + \cdots +f_d \\
	&\le f_3 + 2f_4 + \cdots + (d-2)f_d 
	\end{align*}
  18. Let $v_1,v_2,\ldots,v_m$ and $u_1,u_2,\ldots,u_m$ be the
      vertices of two routes of maximal length. Since the graph is
      connected there is a route from $v_1$ to $u_1$. Then there is a
      sub\-route (with at least one edge) with no edges from the first
      or the second route of maximal length.  Let $v_i$ be the first
      and $u_j$ the last vertex of this sub\-route.  Then $v_i$
      divides the first and $u_j$ divides the second route of maximal
      length into two parts.  Selecting the longer parts from both
      routes and the sub\-route in the middle we get a longer route
      than the routes of maximal length which is a contradiction.
  19. Sketch: Take one route of maximal length, and find its middle
      point $w$.  Then $w$ is an element of each route with maximal
      length.  We know from the previous exercise, that any route of
      maximal length has (at least one) common point with the first
      route of maximal length, and we need to show that $w$ is one of
      these ``common'' points.  Using indirect proof, there are two
      major cases, first $w$ is `before' the common section, and the
      second that $w$ is `after' the common section.  In both cases,
      if we select the part containing $w$ from the first route,
      combine it with the common section, and add a part of the second
      route from the common section to the end (there are two such
      parts, add the one which is longer).
  20. For the number of separating edges see /cut sets/ from the
      lectures.
  21. We need to show that $c+n\ge n$ where:
      - $c$ is the number of components 
      - $e$ is the number of edges and 
      - $n$ is the number of vertices in the graph.  
      Let $e_i$ be the number of edges and $n_i$ the number of
      vertices in the $i$-th component (where $1\le i \le n$).  We
      know that a spanning tree of the $i$-th component has $n_i-1$
      edges so $n_i - 1 \le e_i$ (because a spanning tree is a
      sub\-graph).  If we take the sum on all of the previous
      equations we have 
      \begin{align*}
      \sum_{i=1}^c (n_i - 1) &\le \sum_{i=1}^e_i \\
      \sum_{i=1}^c n_i - \sum_{i=1}^c 1 &\le \sum_{i=1}^e_i \\
      n - c &\le e 
      \end{align*}
  22. Yes.  The first graph contains an open Euler trail, and the
      second a closed Euler line.
  23. Yes.  A square and a triangle connecting at one vertex (like a
      fish).
  24. Yes.  It is a closed walk.  We can obtain it by ``doubling''
      each edge, and making all vertices having even degree.  Then
      there is a closed Euler trail in the ``doubled'' graph, which
      contains all the edges of the original graph exactly twice.
  25. If $d(v)=4$ for all $v\in V$ then there is a closed Euler line
      in the graph.  Coloring the edges of this closed Euler line we
      provide a coloring demanded by the problem.  If the closed Euler
      line with a red edge, it will leave with a blue edge (and vice
      versa).  Every vertex is visited two times by the closed Euler
      line, thus it will have two red and two blue edges.

      This is true for the first/last vertex of the of the closed
      Euler line.  Since $\sum d(v)= 4 \card{V} = 2\card{E}$ we have
      $\card{E} = 2 \card{V}$.  Let's say we start with blue, then
      because there is an even number of edges in the graph, the last
      line in the closed Euler line will be red.
  26. The first and the third graph is not Hamiltonian.  Both of these
      graphs are similar: if we remove the $k$ number of vertices with
      $d(v)=4$ from the middle cycle the graph will be separated into
      the inner cycle, the outer cycle and $k$ isolated vertices from
      the middle (for $k=4$ and $5$).  By problem 31 there is no
      Hamilton cycle in these graphs.  
      
      However, there is a Hamilton cycle in the second graph.
      Informally: start from the top, go down two edges on the right
      side, go one edge to the right most vertex, then across two
      edges, then two edges to the center, from there two steps to the
      lower left vertex and back up (in two steps).
  27. No.  Representation using graphs: $V$ is the set of squares.
      $v_1,v_2\in V$ are connected iff the knight can jump from $v_1$
      to $v_2$.  We need to find a Hamilton cycle, and from a white
      square we can only jump to a black square (and vice versa).  So
      the vertices of the Hamilton cycle need to alternate between
      black and white, but this is impossible because $\card{E}=81$ is
      odd.
  28. 
  29. The Petersen graph is not Hamiltonian.  If you delete any of the
      vertices from it, it is not hard to find a Hamiltonian cycle.
  30. If the graph is Hamiltonian, it contains a Hamilton cycle which
      contains all the vertices of the graph. If we delete an edge
      fond in the Hamilton cycle, all vertices are still connected
      because we are left with a Hamilton route.  If the edge was not
      in the Hamilton cycle, the vertices will remain connected by the
      Hamilton cycle.
  31. Suppose indirectly there is a Hamilton cycle in the graph.  If
      we delete any $k$ vertices from a cycle, it will be split up
      into $\le k$ components, which is a contradiction to splitting it up
      into $\ge k+1$ components.
  32. Suppose indirectly, that $K$ was not a Hamilton cycle.  Then
      there is a vertex $w$ not in $K$.  Because the graph is
      connected, there is a route from $w$ to any vertex of $K$.  Let
      $v$ be the first vertex in $K$ on a route from $w$ to some
      vertex in $K$.  The problem states that if we delete any edge
      from $K$ we get a route of maximal length, so if we delete an
      edge in $K$ with $v$ as an endpoint, we can extend the remaining
      route with the segment of the route to $w$, which would be a
      longer route than a route of maximal length, which gives us a
      contradiction.
  33. 
      1) The $n$ long cycle is a good example.  For $n=5$ and $6$
         should be done manually (for $n=5$ it is trivial, for $n=6 it
         is a bit tricky).  For $n\ge 6$, the complement has $d(v)\ge
         n/2$ so by Dirac's theorem, there has to be a Hamilton cycle.
      2) The star is not Hamiltonian because you can only go one way
         from the center. Neither its complement Hamiltonian because
         the center becomes an isolated vertex.
  34. The vertices are the people, the edges are friendships and a
      seating is a Hamiltonian cycle.  In the beginning the visit
      $d(v)=99$ for each vertex, and after $k$ evenings it
      $d(v)=99-k2$. So after $24$ evenings, $d(v)=99-2\cdot 24=51\ge
      100/2$.  So after 24 evenings, there will still be a Hamiltonian
      cycle in the graph because of Dirac's theorem, so they can stay
      for the 25 day, after which we will have $d(v)=49$ for every
      $v$.
  35. Put all the vertices of the graph on a horizontal straight line
      and make the orientation of each edge go from left to right.
  36. The players are vertices, and there is an arrow (a directed
      edge) from $v_1$ to $v_2$ if $v_1$ beat $v_2$.  After the
      tournament, we have an orientation of a(n undirected) complete
      graph and we need to find a Hamiltonian route in it.  

      We prove this by induction on the number of vertices $=n$.
      - For $n\le2$ it is trivial.
      - Suppose it is true for $n$ and we have the Hamiltonian route
        $v_1,v_2,\ldots v_n$.  If we add a new vertex $v$, then there
        are three options:
	1) $v$ beat $v_1$ (\ie $(v,v_1)\in\psi$), and then
           $v,v_1,\ldots,v_n$ is a Hamiltonian route,
	2) $v$ was beaten by $v_n$ (\ie $(v_n,v)\in\psi$) then
           $v_1,\ldots,v_n,v$ is a Hamiltonian route,
	3) otherwise $v$ was beaten by $v_1$ and $v$ beat $v_n$.  If
           $k$ is the smallest index so that $v_{k}$ beaten by $v$
           (\ie $k=\min\{j: (v,v_j)\in\psi\}$), then $1<k\le n$ and
           $v_{k-1}$ beat $v$ (\ie $(v_{k-1},v_k)\in\psi$), so
           $v_1,\ldots,v_{k-1},v,v_{k},\ldots,v_n$ is a Hamiltonian
           cycle.
  37. The 3d cube, $K_3$ and $K_4$ are planar graphs \ie the can be
      drawn so that their edges don't intersect.  The others are not,
      use Kuratowski's theorem.
  38. Let $e$ be the number of edges, $f$ the number of faces and $n$
      the number of vertices.  In a planar graph, if all regions are
      triangles, then each region is surrounded by 3 edges and every
      edge separates 2 regions.  Therefore the ratio of edges to
      regions $e:f=3:2$ or $e/f=3/2$ so $f=2e/3$.  Euler's formula
      says, $n+f=e+2$ so 
      \begin{align*}
      n+f&=e+2\\
      n+\frac{2}{3}e&=e+2\\
      n-2&=\frac{1}{3}e\\
      e&=3n-6
      \end{align*}
  39. As shown in the previous problem, a planar graph, with all faces
      triangles, the number of edges is $3n-6$ (where $n=\card{V}$).
      In general, if a graph is planar, each face if not a triangle,
      it can be split up into triangles by adding more edges,
      resulting in a graph with triangles for all faces, ergo the
      original triangle must have had $\le 3n-6$ edges.
  40. If a graph is planar, it has at most $3n-6$ edges, the number of
      edges of $G$ and $\overline{G}$ together is $n(n-1)/2$, so if
      both are planar then
      \begin{align*}
      n(n-1)/2 & \le 2\cdot (3n-6)\\
      n^2 - n & \le 12n -24\\
      n^2 -13n + 24 &\le 0.
      \end{align*}
      Since $n_{1,2}=(11\pm\sqrt{169-96})/2=(11\pm\sqrt{73})/2$, and
      $n=(11+\sqrt{73})/2\approx 10.77$ and $n=(11-\sqrt{73})/2\approx
      2.22$.  So if both $G$ and $\overline{G}$ are planar then
      $2.22<n<10.77$ has to be true, that is, if $n\ge11$ then $G$ or
      $\overline{G}$ is not planar.
  41. See this in the footnote
      [fn::http://math.stackexchange.com/questions/480512/maximum-value-for-v-in-planar-self-complementary-graph]
  42. Let $n=\card{V}$ and $e=\card{E}$.  Then $2e=\sum_{v\in V}
      d(v)\ge 6n$, ergo $e \ge 3n$ but in a planar graph $e\le 3n-6$
      which is a contradiction.
  43. As with problem 38: $e/f \ge k/2$ so $f \le 2e/k$ and $n+f=e+2$
      so 
      \begin{align*}
      e=n+f-2 & \le n + \frac{2e}{k} -2\\
      e\left(1-\frac{2}{k}\right) & \le n - 2\\
      e & \le \frac{k(n-2)}{k-2}
      \end{align*}
  44. In a graph representation the capitals of the countries are the
      vertices and two graphs are connected iff the are neighbouring
      countries.  If all 5 of them were from neighbouring countries
      every vertex would have $d(v)=4$, so $\sum_{v\in V} d(v) =
      5\cdot 4 = 20 = 2\card{E}$ so $\card{E}=10$.  But for a planar
      graph, $10= \card{E} \le 3n-6 = 3\cdot 5 - 6 = 9$ which is a
      contradiction.
* COMMENT Old solution
  8. Start of from any vertex $v_0$, and continue on unused
     (untouched) edges and unused vertices.  Since the graph is
     finite, we can do this finite many times.  If the vertexes
     visited are $v_0,v_1,\ldots,v_s$ \ie $v_s$ is the last possible
     vertex visited, then all the neighbors of $v_s$ are already
     visited.  Let $v_k$ be the vertex with the least index which is
     adjacent to $v_s$.  So $v_s,v_k,v_{k+1},\ldots,v_s$ is a cycle,
     and since $d(v_s)\ge k$, so at least $k$ adjacent vertices and
     $v_s$ make at least $k+1$ vertices.
  12. Let $v_1,v_2,\ldots,v_m$ and $u_1,u_2,\ldots,u_m$ be the
      vertices of two routes of maximal length.
  13. 
  14. 
