# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: p-common.org
#+INCLUDE: tikz/graph-common.org
#+LATEX_HEADER: \usepackage[margin=1.5cm]{geometry}

#+TITLE: Discrete mathematics II. practice - Graphs
#+SHORT_TITLE: Graphs

* Graphs
  1. Draw all mutually not isomorphic graphs with 3, 4 and 5 vertices.
     Which of them are connected, which are regular graphs?
  2. Does a graph exist (with at least two vertices) with all vertices
     having different degrees?
  3. Can you find a group of people so each one of them has a different
     number of mutual friends (inside the group)?
  4. Are there graphs (arbitrary or simple) with 9 vertices with the
     following values for the degrees:
     1) $7,7,7,6,6,6,5,5,5$;
     2) $6,6,5,4,4,3,2,2,1$?
  5. Is there a graph with 8 vertices with degrees $6,6,6,6,3,3,2,2$?
  6. How many mutually not isomorphic graphs are there with:
     1) 2 vertices, each with degrees 2, 3 or 4?
     2) 3 vertices, each with degrees 2, 3 or 4?
  7. Show that the number of vertices with odd edges is even.
  8. Draw the following graph!  Specify five points on a circle!  These
     points define $\binom{5}{2}$ chords which will be the vertices of
     the graph.  Two vertices in the graph are connected if and only if
     the corresponding chords don't have a common endpoint.  The
     obtained graph is called the Petersen graph.
  9. Which $C_n$'s are sub\-graphs of the Petersen graph?
  10. How many graphs with 3, 4 or 5 vertices are isomorphic to their
      own complement?
  11. Prove that any closed walk of odd length contains a circle.  
      Is this true for closed walks of even length.
  12. Show that if all vertices in a graph have degrees of at least two, then the graph contains a circle!
  13. Show that if there is a route from $a$ to $b$ and a route from $b$ to $c$ then there is a route from $a$ to $c$.  
  14. Six contestants are competing in a tournament.  
      Prove that at any moment there are three players who all played against each other, or three players who didn't play with the other two.  
  15. Show that if a graph has $2n$ vertices and all of them have degree
      at least $n$, then the graph is connected!   What happens if we
      allow vertices with degree $n-1$?
  16. Is it true, that either the graph $G$ or its complement is always connected?
  17. In a tree, let us denote the number of vertices with degree 1 with $d_1$, and with degree more than 2 with $c$.  
      Show that if there are at least two vertices in the graph $d_1>c+2$ is true.  
  18. Show that in a connected finite graph, each two routes of maximum length have ate least one common vertex.
  19. Show that in a finite tree there is a vertex through which all the routes of maximum length go through.
  20. If the number of vertices in a graph is $n\ge1$, at least how many separating edges (edges which separate the graph into more components if they are removed) are there in the graph?  
      At least how many separating vertices?   
      For both cases provide an example where the number of separating edges (or vertices) equals to the bound.
  21. Show that in a finite graph the sum of the number of components and the number of edges is not less than the number of vertices.  
  22. Can you draw the following graphs without lifting your pen and
      not going over any line more than once (is there an Euler line
      or closed line in the graph).

      \begin{tikzpicture}[scale=0.5]
      \draw[inode] (0,0) node{} 
      -- ++(0,1)  node{} 
      -- ++(-2,0) node{} 
      -- ++(0,3)  node{}
      -- ++(4,0)  node{} 
      -- ++(0,-3) node{}
      -- ++(-2,0) node{} 
      -- ++(0,1)  node{}
      -- ++(-1,0) node{} 
      -- ++(0,1)  node{}
      -- ++(2,0)  node{} 
      -- ++(0,-1) node{}
      -- ++(-1,0) node{} 
      -- ++(0,1)  node{}
      -- ++(0,1)  node{} 
      -- ++(0,1)  node{};
      \end{tikzpicture}
      \begin{tikzpicture}[scale=0.8,inode]
      \def\n{3}
      \foreach \x in {0,...,\n}{
      \draw (0,\x) -- (\n,\x);
      \draw (\x,0) -- (\x,\n);
      \foreach \y in {0,...,\n}{
      \node at (\x,\y) {};
      }
      }
      \draw (0,1) -- (1,0);
      \draw (2,0) -- (3,1);
      \draw (0,2) -- (1,3);
      \draw (2,3) -- (3,2);
      \end{tikzpicture}
  23. Does a graph exist which contains a closed Euler line and has an even number of vertices and odd number of edges.  
  24. Show, that each connected graph contains a walk which contains each edge exactly twice.  
      Is it a closed walk?  
  25. Show that if all vertices have degree 4 then the edges can be coloured red and blue so that each vertex is connected to two red and two blue edges.
  26. Are the following graphs Hamiltonian (or a Hamilton route):\\

      \begin{tikzpicture}[scale=0.65,inode]
      \foreach \s in {0+45,90+45,180+45,270+45}{
      \node at (\s:1) {};
      \node at (\s:2) {};
      \node at (\s:3) {};
      \node at (\s+45:1.41) {};
      \draw [-] 
      (\s:1) -- ({\s+90}:1)
      (\s:2) -- ({\s+90}:2)
      (\s:3) -- ({\s+90}:3)
      (\s:1) -- ({\s}:3);
      }
      \end{tikzpicture}

      \begin{tikzpicture}[scale=0.9]
      \filldraw
      (0:0) circle (3pt);
      \filldraw
      (0:1) circle (3pt)
      (72:1) circle (3pt)
      (144:1) circle (3pt)
      (216:1) circle (3pt)
      (288:1) circle (3pt);
      \filldraw
      (0:2) circle (3pt)
      (72:2) circle (3pt)
      (144:2) circle (3pt)
      (216:2) circle (3pt)
      (288:2) circle (3pt);
      
      \foreach \s in {0,72,144,216,288}{
      \draw [-] (\s:2) -- ({\s+72}:2);
      \draw [-] (\s:0) -- ({\s}:1);
      \draw [-] (\s:2) -- ({\s+72}:1);
      \draw [-] (\s:1) -- ({\s+72}:2);
      }
      \end{tikzpicture}

      \begin{tikzpicture}[scale=0.65]
      \foreach \s in {0,72,144,216,288}{
      \filldraw 
      (\s:1) circle (3pt)
      (\s:2) circle (3pt)
      ({\s+36}:1.63) circle (3pt)
      (\s:3) circle (3pt);
      
      \draw [-] 
      (\s:1) -- ({\s+72}:1)
      (\s:2) -- ({\s+72}:2)
      (\s:3) -- ({\s+72}:3)
      (\s:1) -- ({\s}:3);
      }
      \end{tikzpicture}
  27. Can you jump with a night on a $9\times9$ chess board, touching all the squares and returning to the starting one at the end.  
  28. Show that a pack of dominoes can be arranged in a circle.  
  29. Show that the Petersen graph is not Hamiltonian but deleting a vertex makes it Hamiltonian.  
  30. Show that if a graph is Hamiltonian, then deleting one edge always leaves it connected.  
  31. Show that if there are $k$ vertices which if removed brake the graph up into more than $k$ components, then the original graph is not Hamiltonian.  
  32. Show that if removing an edge from the circle $K$ of a finite connected graph produces a route of maximum length, then $K$ was a Hamilton circle.  
  33. For all $n\ge 5$ show that there exists a graph $G$ with $n$ vertices, (a) so that both $G$ and $\overline{G}$ is Hamiltonian; \hspace{5mm} (b) so that neither $G$ nor $\overline{G}$ are Hamiltonian.  
  34. One hundred friends arrive at a hotel.  
      Each night they are seated at the same table.  
      Also each evening they get into a quarrel with their neighbours and get angry at each other (until the end of their lives).  
      Also, every evening they select their seats so that they don't sit to next to someone who they are angry with.  
      When they can't sit down like this at the table, they all go home.  
      Show that they stay at the hotel for at least 25 days.  
  35. Show that any graph not containing loops can be directed in a way that the resulting directed graph has no directed circle.  
  36. Show that after a tennis tournament all the players can stand in a
      line so that every player has defeated the person standing
      immediately in front off him/her.  
  #  \item 37 TODO
  #  \item 38 TODO
  - Which of these graphs can be drawn so that their edges don't intersect:\\
    (a) the edges of a 3d cube; \hspace{5mm} 
    (b) $K_n$ for $n=3,4,5,\ldots$; \hspace{5mm}
    (c) ``three houses, three wells'' \ie $K_{3,3}$ \hspace{5mm}
    (d) the Petersen graph.
  - How many edges does a planar graph with $n$ vertices have if all of its faces are triangles.  
  - Show that a planar graph with at least $n\ge3$ vertices has at most $3n-6$ edges.  
  - Prove that if the graph $G$ has 11 vertices, then either $G$ or its complement is not planar!
  - Draw a planar graph with 8 vertices so its complement is also planar!  
  - Show that a simple planar graph can not have all vertices with degree at least 6.
  - At most how many edges does a planar graph have if all of its circles are at least $k$ long.  
  - On an international conference representatives of 5 countries are sitting at a table.  
    That there are at least two of them not from neighbouring countries!
  - Show that the faces of a planar graph can be coloured with two colours so that adjacent faces have different colours if and only if the graph contains a closed Euler line.  

** COMMENT Solutions
   1. We drew this in the notebook.
   2. 
      1) Yes, 3 dots above, 4 dots bellow, connect each dot from above
         with each dot bellow.
      2) No, if $n=\card{V}$ \ie $n=7$ in this case, then we can't
         have $n-1$ and $0$ degrees in the same graph
      3) No, $\sum_{v\in V}d(v)$ is odd, but it has to be even.
      4) No, from the 3 vertices with $d(v)=5$ /at least/ $3\cdot 3=9$
         edges are connected with the other 4 edges (if we connect
         each of the 3 five degree vertices), and /at most/
         $2+2+2+1=7$ edges can be connected to the remaining four
         vertices.
      5) No, for each $v\in V$, $0\le d(v) \le n-1$ and there are $n$
         vertices in the graph, so to have all degrees different
         they'd have to be $0,1,2,\ldots,n-1$, but as we saw earlier,
         we can't have $0$ and $n-1$ degree vertices in a simple graph
         at the same time.
   3. Indirect proof:
      - If $G$ is not connected, it has at least two components.
      - The smaller component has at most $n$ vertices.
      - A component with $n$ vertices in a simple graph must have
        $d(v)\le n-1$ for all vertices, which is a contradiction (to
        $d(v)\ge n$ for all vertices).
      This will not be true for only $d(v)\ge n-1$.  For example:
      $n=1$, $2n+1=3$.  Then $3$ isolated vertices, \ie $d(v)=0=n-1$
      for each vertex, and the graph has 3 components, ergo it is not
      connected.
   4. If $G$ is connected we are done!  If $G$ is disconnected there
      are at least two components.  Any vertices $v$ and $v'$ are
      either in one component or in different components.
      - If $v$ and $v'$ are in different components, there and edge
        between them in $\overline{G}$.
      - If $v$ and $v'$ are in the same component, then there is at
        least one more component with at least one vertex in it, let's
        it be the vertex $z$.  $z$ is not connected to $v$ nor $v'$ so
        in $G$, so in $\overline{G}$ there is and route from $v$
        through $z$ to $v'$.
   5. Start of from any vertex $v_0$, and continue on unused
      (untouched) edges and unused vertices.  Since the graph is
      finite, we can do this finite many times.  If the vertexes
      visited are $v_0,v_1,\ldots,v_s$ \ie $v_s$ is the last possible
      vertex visited, then all the neighbors of $v_s$ are already
      visited.  Let $v_k$ be the vertex with the least index which is
      adjacent to $v_s$.  So $v_s,v_k,v_{k+1},\ldots,v_s$ is a cycle,
      and since $d(v_s)\ge k$, so at least $k$ adjacent vertices and
      $v_s$ make at least $k+1$ vertices.
   6. Draw then!
   7. Reformulate the problem to the domain of graphs: we need to
      prove for each 6 vertex simple graph $G$, there is triangle in
      $G$ or $\overline{G}$.
   8. Proofs:
      - Let $n=\card{V}$ \ie the number of vertices and
        \[f_i=\card{\{v\in V:d(v)=i\}}\] \ie $f_i$ is the number of
        vertices with degree $i$, with $d=\max\{d(v):v\in V\}$ then:
	\begin{align}
	n &= f_1+f_2+\cdots+f_d \label{f1one} \\
	\sum_{v\in V} d(v) &= f_1 + 2f_2 + \cdots +df_d \label{f1two}
	\end{align}
      - Because in a tree graph, the number of edges is $n-1$ ergo
        $\sum_{v\in V} d(v) = 2\card{E}=2n-2$.  So by multiplying
        \eqref{f1one} we get
	\begin{equation}
	\label{f1three}
	2n = 2f_1 + 2f_2 + \cdots 2f_d
	\end{equation}
	Subtracting \eqref{f1two} from \eqref{f1three} we get \[ 2 =
        f_1 - f_3 - 2f_4 - \cdots - (d-2)f_d \] or rearranging the
        previous equation: \[ f_1 = 2 + f_3 + 2f_4 + \cdots (d-2)f_d
        \ge 2 + c\] because 
	\begin{align*}
	c &= f_3 + f_4 + \cdots +f_d \\
	&\le f_3 + 2f_4 + \cdots + (d-2)f_d 
	\end{align*}
   9. Let $v_1,v_2,\ldots,v_m$ and $u_1,u_2,\ldots,u_m$ be the
      vertices of two routes of maximal length.
   10. 
   11. 
