# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: p-common.org
#+LATEX_HEADER: \usepackage[margin=1.5cm]{geometry}

#+TITLE: Discrete mathematics II. practice - Graphs
#+SHORT_TITLE: Graphs

* Graphs
  1. Draw all, pairwise not isomorphic simple graphs with $2,3,4$ and
     $5$ vertices.  How many of them are connected and how many
     regular graphs are there?
  2. Are there simple graphs with 7 vertices, with the following
     degrees:
     1) $4,4,4,3,3,3,3$
     2) $6,3,3,2,2,2,0$
     3) $5,5,5,4,4,2,2$
     4) $5,5,5,2,2,2,1$
     5) All degrees different?
  3. Let $n\in\N$ and $G=(\varphi,E,V)$ a simple graph, with at most
     $2n+1$ vertices.  Prove that if for each $v\in V$ $d(v)\ge n$,
     then $G$ is connected.  Will this be true, if only $d(v)\ge n-1$
     is demanded for every vertex.
  4. If $G$ is a finite simple graph, the $G$ or $\overline{G}$ is
     connected.
  5. Prove that if in a finite simple graph every vertex $v$ has
     $d(v)\ge k$ (where $k\ge2$), then there is a cycle in the graph
     with at least $k+1$ vertices.
  6. Count all the 4 and 5 vertex graphs which are isomorphic to their
     complement.
  7. Six contenders are competing in a tournament (everyone competes
     with everyone else).  Prove that at each moment, there are three
     contenders which all played with each other, or there are three
     contenders so that none of them played with each other.
  8. In a tree graph, let $f_1$ be the number of vertices with degree
     equal to 1, and $c$ the number of vertices with degree grater
     than 2.  Prove that $f_1 \ge c + 2$.
  9. Show, that in a finite connected graph, any two of maximal length
     routes has a common vertex.
  10. Show, that in a finite tree, all the routes of maximal length
      visit a common vertex.
  11. Let $n>1$ an integer:
      1) At most how many separating edges are in a graph with $n$
         vertices?  Provide a graph with exactly this many separating
         edges.
      2) At most how many separating vertices are in a graph with $n$
         vertices?  Provide a graph with exactly this many separating
         vertices.
  12. Is there a graph with a closed Euler line, with even number of
      vertices and odd number of edges?
  13. Show that in a graph without loop edges with all vertices with
      degree 4, then we can paint the edges blue and red so that there
      are two red and two blue edges connected to each vertex.
#+BEGIN_COMMENT
2.1-14. Mutassuk meg, hogy egy körmérk®zéses pingpongverseny résztvev®i
sorba állíthatók úgy, hogy mindenki legy®zte a közvetlenül mögötte állót. (Azt
nem követeljük meg, hogy az összes mögötte állót le kellett volna gy®znie.)

2.1-15. Legyen k pozitív egész. Igazoljuk a következ®ket:
• Ha egy véges összefügg® gráfban van k olyan csúcs, melyek elhagyásával
#+END_COMMENT

** Solutions
   1. We drew this in the notebook.
   2. 
      1) Yes, 3 dots above, 4 dots bellow, connect each dot from above
         with each dot bellow.
      2) No, if $n=\card{V}$ \ie $n=7$ in this case, then we can't
         have $n-1$ and $0$ degrees in the same graph
      3) No, $\sum_{v\in V}d(v)$ is odd, but it has to be even.
      4) No, from the 3 vertices with $d(v)=5$ /at least/ $3\cdot 3=9$
         edges are connected with the other 4 edges (if we connect
         each of the 3 five degree vertices), and /at most/
         $2+2+2+1=7$ edges can be connected to the remaining four
         vertices.
      5) No, for each $v\in V$, $0\le d(v) \le n-1$ and there are $n$
         vertices in the graph, so to have all degrees different
         they'd have to be $0,1,2,\ldots,n-1$, but as we saw earlier,
         we can't have $0$ and $n-1$ degree vertices in a simple graph
         at the same time.
   3. Indirect proof:
      - If $G$ is not connected, it has at least two components.
      - The smaller component has at most $n$ vertices.
      - A component with $n$ vertices in a simple graph must have
        $d(v)\le n-1$ for all vertices, which is a contradiction (to
        $d(v)\ge n$ for all vertices).
      This will not be true for only $d(v)\ge n-1$.  For example:
      $n=1$, $2n+1=3$.  Then $3$ isolated vertices, \ie $\d(v)=0=n-1$
      for each vertex, and the graph has 3 components, ergo it is not
      connected.
   4. If $G$ is connected we are done!  If $G$ is disconnected there
      are at least two components.  Any vertices $v$ and $v'$ are
      either in one component or in different components.
      - If $v$ and $v'$ are in different components, there and edge
        between them in $\overline{G}$.
      - If $v$ and $v'$ are in the same component, then there is at
        least one more component with at least one vertex in it, let's
        it be the vertex $z$.  $z$ is not connected to $v$ nor $v'$ so
        in $G$, so in $\overline{G}$ there is and route from $v$
        through $z$ to $v'$.
   5. Start of from any vertex $v_0$, and continue on unused
      (untouched) edges and unused vertices.  Since the graph is
      finite, we can do this finite many times.  If the vertexes
      visited are $v_0,v_1,\ldots,v_s$ \ie $v_s$ is the last possible
      vertex visited, then all the neighbors of $v_s$ are already
      visited.  Let $v_k$ be the vertex with the least index which is
      adjacent to $v_s$.  So $v_s,v_k,v_{k+1},\ldots,v_s$ is a cycle,
      and since $d(v_s)\ge k$, so at least $k$ adjacent vertices and
      $v_s$ make at least $k+1$ vertices.
   6. Draw then!
   7. Reformulate the problem to the domain of graphs: we need to
      prove for each 6 vertex simple graph $G$, there is triangle in
      $G$ or $\overline{G}$.
   8. Proofs:
      - Let $n=\card{V}$ \ie the number of vertices and
        \[f_i=\card{\{v\in V:d(v)=i\}}\] \ie $f_i$ is the number of
        vertices with degree $i$, with $d=\max\{d(v):v\in V\}$ then:
	\begin{align}
	n &= f_1+f_2+\cdots+f_d \label{f1one} \\
	\sum_{v\in V} d(v) &= f_1 + 2f_2 + \cdots +df_d \label{f1two}
	\end{align}
      - Because in a tree graph, the number of edges is $n-1$ ergo
        $\sum_{v\in V} d(v) = 2\card{E}=2n-2$.  So by multiplying
        \eqref{f1one} we get
	\begin{equation}
	\label{f1three}
	2n = 2f_1 + 2f_2 + \cdots 2f_d
	\end{equation}
	Subtracting \eqref{f1two} from \eqref{f1three} we get \[ 2 =
        f_1 - f_3 - 2f_4 - \cdots - (d-2)f_d \] or rearranging the
        previous equation: \[ f_1 = 2 + f_3 + 2f_4 + \cdots (d-2)f_d
        \ge 2 + c\] because 
	\begin{align*}
	c &= f_3 + f_4 + \cdots +f_d \\
	&\le f_3 + 2f_4 + \cdots + (d-2)f_d 
	\end{align*}
   9. Let $v_1,v_2,\ldots,v_m$ and $u_1,u_2,\ldots,u_m$ be the
      vertices of two routes of maximal length.
   10. 
   11. 
