# -*- mode: org; mode: flyspell -*-
#+INCLUDE: inc-test.org
# Set no title
#+BIND: org-latex-title-command ""

* First sample test - Discrete mathematics 2.
  1. Draw a simple 7 vertex graphs with the following degrees or prove
     that such a graph doesn't exist:
     #+ATTR_LATEX: :environment inparaenum
     1) $6, 5, 5, 5, 3, 2, 2$;
     2) $6, 5, 5, 5, 3, 3, 3$;
     3) $6, 5, 5, 5, 3, 5, 2$;
     4) $6, 4, 4, 4, 2, 2, 0$.
  2. Six contestants are competing in a tournament.  Prove that at
     any moment there are three players who all played against each
     other, or three players who didn't play with the other two.
  3. Show, that each connected graph contains a walk which contains
     each edge exactly twice.  Is it a closed walk?
  4. Show that $(E,\cdot)$ is a group where
     $E=\cup_{n\in\mathbb{N}}\{x\in\mathbb{C}:x^n=1\}$ and the
     operation is the usual multiplication defined on complex numbers.

     See http://mathworld.wolfram.com/Group.html.
  5. Show that if the inverse of every element in a group is the
     element itself, then the group is commutative.  
  6. Show $\varphi(a)=\frac{1}{2} (\begin{smallmatrix} a & a \\ a & a
     \end{smallmatrix})$ there is a homo\-morphism from $(G,\cdot)$ to
     $(G',*)$ where $G=\mathbb{R}\setminus\{0\}$ with the usual
     multiplication defined on the real numbers and
     $G'=\left\{(\begin{smallmatrix}a & a \\ a & a\end{smallmatrix}) :
     a\neq 0, a\in \mathbb{R} \right\}$ with the matrix multiplication
     for $\mathbb{R}^{2\times2}$ matrices.
     
     See http://mathworld.wolfram.com/GroupHomomorphism.html.
  7. In the dihedral group $D_n$ for $n=12$ and the elements of the
     group $g_1=\tau \circ \varepsilon^4 \circ \tau^5$, $g_2=\tau^{25}
     \circ \varepsilon^{21}$ answer the following questions:
     #+ATTR_LATEX: :environment inparaenum
     1) What is the order of $D_n$?
     2) Simplify $g_1$, $g_2$ and $g_1\circ g_2$.
     3) What are the sub\-group generated by $g_1$, $g_2$ and
        $g_1\circ g_2$?
     4) What is the order of $g_1$, $g_2$ and $g_1\circ g_2$?


     See https://en.wikipedia.org/wiki/Dihedral_group.

* Solutions
  1. 
     1) Not possible, see the argument for exercise 5.
     2) Possible, try to draw it.  First draw $K_4$ (the will be the
        vertices with degrees $6, 5, 5, 5$), and connect the remaining
        edges from the $6$ degree vertex to the last three vertices.
        The rest is up to you!
     3) Not possible, $\sum_{v\in V}d(v)$ is odd, see lectures.
     4) Not possible, see exercise 2 in p1-graphs-dm2.pdf.
  2. See exercise 14.
  3. See exercise 24.
  4. Let $E_n=\{x\in\mathbb{C}:x^n=1\}$, then
     $E=\cup_{n\in\mathbb{N}}E_n$ so $x\in E$ if there is a natural
     number $n$ so that $x^n=1$.  

     To prove that $E$ is a group, first we need to show that it is a
     groupoid: if $x,y\in E$ then there exists $n,m\in\mathbb{N}$ so
     that $x^n=1$ and $y^m=1$, but then $(x^n)^m=x^{nm}=1$ and
     $(y^m)^n=y^{nm}=1$, so $(xy)^{nm}=x^{nm}y^{nm}=1$ so $xy\in
     E_{nm}$ ergo $xy\in E$ \ie $(E,\cdot)$ is a groupoud.
     
     Next, we need to prove that $E$ is a semi\-group, \ie that the
     operation is associative.  Because $E\subset \mathbb{C}$ and
     $x(yz) = (xy)z$ for any $x,y,z\in\mathbb{C}$, associativity will
     also be true for all elements of $E$.
     
     The element of unity for multiplication in $\mathbb{C}$ is $1$,
     and $e=1$ is the element of unity for $E$ also, because $1^n=1$ for
     any $n\in\mathbb{N}$ so $1\in E_n$ and $1\in E$ is also true.

     To show that $E$ is a group, we have to show that every element
     has an inverse.  In $\mathbb{C}$, the multiplicative inverse of
     $x$ is $\frac{1}{x}$, so we need to check if $\frac{1}{x}\in E$
     is true.  If $x\in E$ then there is a non-negative integer $n$,
     so that $x^n=1$ but then
     $\left(\frac{1}{x}\right)^n=\frac{1}{x^n}=\frac{1}{1}=1$ is true,
     so $\frac{1}{x}\in E_n$ which implies $\frac{1}{x}\in E$.  And of
     course $x\cdot \frac{1}{x} = 1=e$ is also true, \ie it /is/ the
     inverse of $x$.
  5. We need to show $a\cdot b=b\cdot a$ for each $a,b\in G$.  For
     each $x\in G$, $x^{-1}=x$ ergo $x\cdot x=x^2=e$.  So if $x=a\cdot
     b$ then
     \begin{align*}
     (a\cdot b)\cdot (a\cdot b)&=e &\text{ multiply with $a$ from left}\\
     a\cdot (a\cdot b)\cdot (a\cdot b)&=a &\text{ simplify with $a\cdot a=e$}\\
     b \cdot (a \cdot b) &= a &\text{ multiply with $b$ from right}\\
     b \cdot (a \cdot b) \cdot b &= a\cdot b &\text{ simplify with $b\cdot b=e$}\\
     b\cdot a = a \cdot b
     \end{align*}
  6. The problems text was corrected: the $\varphi$ function was not
     defined.
     
     We need to show that $\varphi(a)*\varphi(b)=\varphi(a\cdot b)$.

     \begin{equation*}
     \varphi(a)*\varphi(b)=
     \frac{1}{2}\begin{pmatrix}a&a\\a&a\end{pmatrix}*
     \frac{1}{2}\begin{pmatrix}b&b\\b&b\end{pmatrix}=
     \frac{1}{4}\begin{pmatrix}2ab&2ab\\2ab&2ab\end{pmatrix}=
     \frac{1}{2}\begin{pmatrix}ab&ab\\ab&ab\end{pmatrix}=
     \varphi(a\cdot b)
     \end{equation*}
     
     This is enough if $\varphi$ is known. but if $\varphi$ is not
     known, you can figure out what it is as follows.  Suppose
     $\varphi(a) = \bigl(\begin{smallmatrix} a'&a'\\a'&a'
     \end{smallmatrix}\bigr)$ and
     $\varphi(e)=\bigl(\begin{smallmatrix} e'&e'\\e'&e'
     \end{smallmatrix}\bigr)$, then:
     \begin{equation*}
     \varphi(a)=
     \varphi(a e)=
     \varphi(a)*\varphi(e)=
     \begin{pmatrix}a'&a'\\a'&a'\end{pmatrix} *
     \begin{pmatrix}e'&e'\\e'&e'\end{pmatrix} =
     \begin{pmatrix}2a'e'&2a'e'\\2a'e'&2a'e'\end{pmatrix}
     \end{equation*}
     So $a'=(ae)'=2a'e'$, so $e'=\frac{1}{2}$, then $\varphi(1) =
     \frac{1}{2}(\begin{smallmatrix}1&1\\1&1\end{smallmatrix})$
     because all $(\begin{smallmatrix} a'&a'\\a'&a'
     \end{smallmatrix})$ matrices are obtained as
     $c(\begin{smallmatrix} a&a\\a&a \end{smallmatrix})$ for some
     $c\in \mathbb{R}\setminus\{0\}$ so from this we can obtain that
     not only for $1$ but for any $a\in\mathbb{R}\setminus\{0\}$,
     $\varphi(a)=\frac{1}{2}\begin{smallmatrix} a&a\\a&a
     \end{smallmatrix}$.
  7. 
     1. The order of $D_n$ is $\lvert D_n \rvert=2n$ so in this case $24$.

	There four rules to remember: 
	#+ATTR_LATEX: :environment inparaenum
	1) $\varepsilon^n=e$;
	2) $\tau^2=e$;
	3) $\varepsilon^{-k}=\varepsilon^{n-k}$;
	4) $\tau \circ \varepsilon^{k} = \varepsilon^{n-k}\circ\tau$;
     2. So: 
	- $g_1=\tau \circ \varepsilon^4 \circ \tau^5=\tau \circ
          \varepsilon^4 \circ \tau = \tau \circ \tau \circ
          \varepsilon^{12-4}=\varepsilon^8$,
	- $g_2=\tau^{25} \circ \varepsilon^{21} =\tau \circ
          \varepsilon^{9}$
	- $g_1\circ g_2=\varepsilon^8 \circ \tau \circ \varepsilon^9 =
          \tau \circ \varepsilon^{4+9} = \tau \circ \varepsilon$
     3. 
        - $\langle g_1 \rangle = \{e, \varepsilon^4, \varepsilon^8\}$
          because $(12,8)=4$.  You can prove that if $\langle
          \varepsilon^k \rangle=\langle \varepsilon^d \rangle$ where
          $d=(n,k)$.
        - $\langle g_2 \rangle = \{e, \tau \circ \varepsilon^9\}$,
          because $(\tau\circ\varepsilon^9)^2=\tau\circ\varepsilon^9
          \circ \tau \circ \varepsilon^9 = \varepsilon^3 \circ \tau
          \circ \tau \circ \varepsilon^9 = \varepsilon^{12}=e$.
        - $\langle g_1 \circ g_2 \rangle = \{e, \tau \circ
          \varepsilon\}$, similarly as with the previous sub\-problem.
     4. The order of an element is the same of as the order of the
        sub\-group generated by that element, so $\lvert g_1 \rvert=3$,
        $\lvert g_2 \rvert=2$ and $\lvert g_1 \circ g_2 \rvert=2$.
